config/routes.rb
OmNomNom::Application.routes.draw do
  get "routines/new"
  get "routines/index"
  get "routines/show"
  get "routines/edit"
  root to: 'poses#index'
  get "poses/new"
  get "poses/index"
  get "poses/create"
  devise_for :users
  resources :poses
  resources :routines

end

app/models/pose.rb
class Pose < ActiveRecord::Base
  belongs_to :user
end

app/models/routine.rb
class Routine < ActiveRecord::Base
  belongs_to :user
# has_many :poses
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/poses_controller.rb
class PosesController < ApplicationController
  before_action :authenticate_user!, except: :index

  def new
  end

  def index
    @poses = Pose.all
  end

  def create
    @pose = Pose.create!(post_params.merge(user: current_user))
    flash[:notice] = "Pose created!";
    redirect_to poses_path 
  end

  def show
    @pose = Pose.find_by_id(params[:id])
  end

  private

    def post_params
      params.require(:pose).permit(:name, :description, :difficulty, :equipment_needed, :tips, :good_for)
    end
end

app/controllers/routines_controller.rb
class RoutinesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :create]

  def new
    @poses = Pose.all
  end

  def index
    @routines = Routine.all
  end

  def show
    @routine = Routine.find(params[:id])
  end

  def edit
  end

  def create
    @routine = Routine.create!(post_params.merge(user: current_user))
    flash[:notice] = "Routine created!"
    redirect_to routines_path
  end

  private

    def post_params
      params.require(:routine).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/poses_helper.rb
module PosesHelper
end

app/helpers/routines_helper.rb
module RoutinesHelper
end

app/views/layouts/_footer.html.erb
<footer>This is my fourth Rails app! Check out the <a href="https://github.com/jimmylorunning/om-nom-nom">source on github</a> or <a href="http://jimmylocoding.com">my coding blog</a> and give me some feedback!</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse navbar-fixed-top">
	<div class="container">
		<div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
	      <span class="sr-only">Toggle navigation</span>
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
      </button>
			<a class="navbar-brand" href="/">Om Nom Nom</a>
		</div>
		<div class="collapse navbar-collapse">
			<ul class="nav navbar-nav pull-right">
			<% if user_signed_in? %>
				<li><%= link_to "Welcome, #{current_user.email}!", edit_user_registration_path %></li>
				<li><%= link_to "Sign out", destroy_user_session_path, :method => 'delete' %></li>
			<% else %>
				<li><%= link_to "Sign in", new_user_session_path %></li>
				<li><%= link_to "Sign up", new_user_registration_path %></li>
			<% end %>
			</ul>
		</div>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Om Nom Nom</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <div class="row">
    <div class="page-area">
      <% flash.each do |key, value| %>
	    <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
	</div>
</div>
</body>
</html>

app/views/poses/create.html.erb
<h1>Poses#create</h1>
<p>Find me in app/views/poses/create.html.erb</p>

app/views/poses/index.html.erb
<h1>Poses#index</h1>
<ul>
<% @poses.each do |pose| %>
  <li><%= link_to pose.name, pose_path(pose) %></li>
<% end %>
</ul>
<%= link_to 'Add Pose', new_pose_path, class: 'btn btn-default' %>

app/views/poses/new.html.erb
<h1>New Pose</h1>
<%= form_for :pose, :html => { class: 'form-horizontal pose-form' }, :url => poses_path do |f| %>
  <div class="form-group">
    <%= f.label :name, class: 'col-sm-2 control-label' %>
    <div class='col-sm-10'>
      <%= f.text_field :name, class: 'form-control', :required => true %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-sm-offset-2 col-sm-10'>
      <%= f.submit "Add New Pose", class: 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/poses/show.html.erb
<h1><%= @pose.name %></h1>

app/views/routines/edit.html.erb
<h1>Routines#edit</h1>
<p>Find me in app/views/routines/edit.html.erb</p>

app/views/routines/index.html.erb
<h1>Routines#index</h1>
<ul>
<% @routines.each do |routine| %>
  <li><%= link_to routine.name, routine_path(routine) %></li>
<% end %>
</ul>

app/views/routines/new.html.erb
<h1>Routines#new</h1>
<%= form_for :routine, :html => { class: 'form-horizontal pose-form' }, url: routines_path do |f| %>

  <div class="form-group">
    <%= f.label :name, class: 'col-sm-2 control-label' %>
    <div class='col-sm-10'>                   
      <%= f.text_field :name, class: 'form-control', required: true %>
    </div>
  </div>
  
  <table class="table table-striped posts-table">
  <% @poses.each do |pose| %>
    <tr><td><%= pose.name %></td><td><%= f.check_box pose.id %></td></tr>
  <% end %>
  </table>

  <div class="form-group">
    <div class='col-sm-offset-2 col-sm-10'>
      <%= f.submit "Add Routine", class: 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/routines/show.html.erb
<h1><%= @routine.name %></h1>